version: '{build}'
clone_depth: 10 # to allow queued build jobs
image:
- Visual Studio 2019
- Ubuntu

matrix:
  stack: jdk 13
  stack: jdk 12
  stack: jdk 11
  stack: jdk 10
  stack: jdk 9
  stack: jdk 8

install:
- cmd: set "JAVA_HOME=C:\Program Files\Java\jdk13"
- mvn --version
- git clone https://github.com/DatavenueLiveObjects/Payload-decoders.git
- cmd: mvn install:install-file -Dfile="Payload-decoders\lib\lo-js-decoder-test-framework-utils-1.2.3-jar-with-dependencies.jar" -DgroupId="com.orange.lo" -DartifactId="lo-js-decoder-test-framework-utils" -Dversion="1.2.3" -Dpackaging="jar"
- sh: mvn install:install-file -Dfile="Payload-decoders/lib/lo-js-decoder-test-framework-utils-1.2.3-jar-with-dependencies.jar" -DgroupId="com.orange.lo" -DartifactId="lo-js-decoder-test-framework-utils" -Dversion="1.2.3" -Dpackaging="jar"

build_script:
- cd Payload-decoders
- cd lo-js-decoder-test-framework-samples
- ps: (Get-Content pom.xml).replace('1.2.2', '1.2.3').replace('1.16.10', '1.16.22') | Set-Content pom.xml
- mvn install

test_script:
- mvn test
