version: '{build}'
image:
- Visual Studio 2017
platform:
- x64
- Win32
configuration: Release

environment:
  file: my.log
  matrix:
  - task: 1
  - task: 2
  - task: 3

init:
- set MYDIR=C:\mycache

cache:
- '%MYDIR%'

before_build:
- if not exist %MYDIR% mkdir %MYDIR%
- dir %MYDIR%
- if exist %MYDIR%\%file% type %MYDIR%\%file%

build_script:
- echo %DATE% %TIME% task %task% %platform% >>%MYDIR%\%file%

after_build:
- dir %MYDIR%
- type %MYDIR%\%file%
