version: '{build}'
clone_depth: 10 # to allow queued build jobs

environment:
  matrix:
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
#      JAVA_HOME: C:\Program Files\Java\jdk13
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
#      JAVA_HOME: C:\Program Files\Java\jdk12
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
#      JAVA_HOME: C:\Program Files\Java\jdk11
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#      JAVA_HOME: C:\Program Files\Java\jdk10
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#      JAVA_HOME: C:\Program Files\Java\jdk9
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
#      JAVA_HOME: C:\Program Files\Java\jdk1.8.0
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
#      JAVA_HOME: C:\Program Files\Java\jdk1.7.0
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      JAVA_HOME: /usr/lib/jvm/java-7-openjdk-amd64
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      JAVA_HOME: /usr/lib/jvm/java-9-openjdk-amd64
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      JAVA_HOME: /usr/lib/jvm/java-10-openjdk-amd64
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      JAVA_HOME: /usr/lib/jvm/java-12-openjdk-amd64
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      JAVA_HOME: /usr/lib/jvm/java-13-openjdk-amd64
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      JAVA_HOME: /usr/lib/jvm/java-14-openjdk-amd64

install:
- sh: ls -l /usr/lib/jvm
- mvn --version
- git clone https://github.com/DatavenueLiveObjects/Payload-decoders.git
- cmd: mvn install:install-file -Dfile="Payload-decoders\lib\lo-js-decoder-test-framework-utils-1.2.3-jar-with-dependencies.jar" -DgroupId="com.orange.lo" -DartifactId="lo-js-decoder-test-framework-utils" -Dversion="1.2.3" -Dpackaging="jar"
- sh: mvn install:install-file -Dfile="Payload-decoders/lib/lo-js-decoder-test-framework-utils-1.2.3-jar-with-dependencies.jar" -DgroupId="com.orange.lo" -DartifactId="lo-js-decoder-test-framework-utils" -Dversion="1.2.3" -Dpackaging="jar"

build_script:
- cd Payload-decoders
- cd lo-js-decoder-test-framework-samples
- ps: (Get-Content pom.xml).replace('1.2.2', '1.2.3').replace('1.16.10', '1.16.22') | Set-Content pom.xml
- mvn install

test_script:
- mvn test
