version: '{build}'
clone_depth: 10 # to allow queued build jobs
image:
- Visual Studio 2017

environment:
  # Use cygwin embeded gettext tools
  path: '%path%;C:\cygwin64\bin'

init:
- git clone https://github.com/DatavenueLiveObjects/Payload-decoders.git

build:
- cd Payload-decoders\lo-js-decoder-test-framework-samples
- mvn clean install

test:
- mvn test
