version: '{build}'
image:
- Visual Studio 2017
platform:
- x64
- Win32
configuration:
- Release
#- Debug

matrix:
  exclude:
  # not installed
  - { comp: 110, image: Visual Studio 2017 }
  - { comp: 141, image: Visual Studio 2015 }
  # duplicated - select only one
  - { comp: 120, image: Visual Studio 2015 }
  - { comp: 140, image: Visual Studio 2015 }

environment:
  matrix:
  # - comp: 110
  # - comp: 120
  # - comp: 140
  - comp: 141
  # - { comp: 110, xp: _xp }
  # - { comp: 120, xp: _xp }
  # - { comp: 140, xp: _xp }
  - { comp: 141, xp: _xp }

init:
### Set MSVS environment
# AppVeyor missing paths
- if "%VS150COMNTOOLS%"=="" set "VS150COMNTOOLS=%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\Common7\Tools\"
# Set developer command prompt
- if %platform:~-2%==64 (set arch=amd64) else (set arch=amd64_x86)
- if %comp% LSS 120 if %platform:~-2%==64 (set arch=x86_amd64) else (set arch=x86)
- call set "vcvarsall=%%VS%comp%COMNTOOLS%%..\..\VC\vcvarsall.bat"
- if %comp%==141 set "vcvarsall=%VS150COMNTOOLS%..\..\VC\Auxiliary\Build\vcvarsall.bat"
- call "%vcvarsall%" %arch%
- echo %APPVEYOR_BUILD_WORKER_IMAGE% %platform% v%comp%%xp% %configuration% %arch%
#info
- dir /n/b/s
  "%ProgramFiles(x86)%\ucrtbase*.dll"
  "%ProgramFiles(x86)%\msvcp*.dll"
  "%ProgramFiles(x86)%\msvcr*.dll"
  "%ProgramFiles(x86)%\vcruntime*.dll"
  "%ProgramFiles(x86)%\concrt*.dll"

install:
- curl -fsSL -O https://github.com/Microsoft/vswhere/releases/download/2.1.3/vswhere.exe
- vswhere -all -prerelease -products "*"
- vswhere -all -prerelease -legacy

# Microsoft.Component.MSBuild
# Microsoft.Component.VC.Runtime.UCRTSDK
# Microsoft.VisualStudio.ComponentGroup.ArchitectureTools.Native
# Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Core
# Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Win81
# Microsoft.VisualStudio.ComponentGroup.NativeDesktop.WinXP
# Microsoft.VisualStudio.Component.Windows10SDK
# Microsoft.VisualStudio.Component.Windows10SDK.15063.Desktop
# Microsoft.VisualStudio.Component.Windows10SDK.14393
# Microsoft.VisualStudio.Component.Windows81SDK
# Microsoft.VisualStudio.Component.WinXP
# Microsoft.VisualStudio.Component.VC.CMake.Project
# Microsoft.VisualStudio.Component.VC.Tools.x86.x64
# Microsoft.VisualStudio.Component.VC.140
# Microsoft.VisualStudio.Component.VC.CLI.Support
# Microsoft.VisualStudio.Component.VC.Modules.x86.x64


build_script:
- cd %APPVEYOR_BUILD_FOLDER%
- mkdir build & cd build
- if %comp%==110 (set "gen=11 2012" & set "tool=v%comp%%xp%")
- if %comp%==120 (set "gen=12 2013" & set "tool=v%comp%%xp%,host=x64")
- if %comp%==140 (set "gen=14 2015" & set "tool=v%comp%%xp%,host=x64")
- if %comp%==141 (set "gen=15 2017" & set "tool=v%comp%%xp%,host=x64")
- if %platform:~-2%==64 set "gen=%gen% Win64"
- cmake -T %tool% -G "Visual Studio %gen%" ..

test: off
