version: '{build}'
image:
# - Previous Visual Studio 2013
- Visual Studio 2013
# - Previous Visual Studio 2015
- Visual Studio 2015
# - Previous Visual Studio 2017
- Visual Studio 2017
platform:
#- x64
- Win32
configuration:
- Release
#- Debug

environment:
  matrix:
  - comp: 90
  - comp: 100
  - comp: 110
  - comp: 120
  - comp: 140
  - comp: 141
  - comp: 150

init:
- if %platform:~-2%==64 (set arch=amd64) else (set arch=amd64_x86)
- if %comp%==110 if not %platform:~-2%==64 set arch=x86
- if %comp%==100 if %platform:~-2%==64 (set arch=x64) else (set arch=x86)
- echo %APPVEYOR_BUILD_WORKER_IMAGE% %platform% v%comp% %configuration% %arch%
# Set MSVS environment
- if "%VS150COMNTOOLS%"=="" set "VS150COMNTOOLS=%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\Common7\Tools\"
- if "%WINDOWS71SDK%"=="" set "WINDOWS71SDK=%ProgramFiles%\Microsoft SDKs\Windows\v7.1\Bin\"
- if "%WINDOWS61SDK%"=="" set "WINDOWS61SDK=%ProgramFiles%\Microsoft SDKs\Windows\v6.1\Bin\"
- if %comp%==141  call "%VS150COMNTOOLS%..\..\VC\Auxiliary\Build\vcvarsall.bat" %arch%
- if %comp%==140 (call "%VS140COMNTOOLS%VsDevCmd.bat" & call "%VS140COMNTOOLS%..\..\VC\vcvarsall.bat" %arch%)
- if %comp%==120 (call "%VS120COMNTOOLS%VsDevCmd.bat" & call "%VS120COMNTOOLS%..\..\VC\vcvarsall.bat" %arch%)
- if %comp%==110 (call "%VS110COMNTOOLS%VsDevCmd.bat" & call "%VS110COMNTOOLS%..\..\VC\vcvarsall.bat" %arch%)
- if %comp%==100  call "%WINDOWS71SDK%SetEnv.cmd" /%arch% /%configuration%
- if %comp%==90   call "%WINDOWS61SDK%SetEnv.cmd" /%arch% /%configuration%
#info
- where vswhere || exit 0

install:
- curl -fsSL -O https://github.com/Microsoft/vswhere/releases/download/latest/vswhere.exe
- vswhere -?

build_script:
- cd %APPVEYOR_BUILD_FOLDER%
- mkdir build & cd build
- if "%APPVEYOR_BUILD_WORKER_IMAGE:~-4%"=="2013" set "gen=12 2013"
- if "%APPVEYOR_BUILD_WORKER_IMAGE:~-4%"=="2015" set "gen=14 2015"
- if "%APPVEYOR_BUILD_WORKER_IMAGE:~-4%"=="2017" set "gen=15 2017"
- if %platform:~-2%==64 set "gen=%gen% Win64"
- cmake -T v%comp%,host=x64 -G "Visual Studio %gen%" ..

test: off
