version: '{build}'
image:
- Visual Studio 2017
platform:
- x64
- Win32
configuration: Release

environment:
  matrix:
  - task: 1
  - task: 2
  - task: 3

init:
- set MYDIR=C:\mycache

cache:
- '%MYDIR%'

install:
- dir %MYDIR%
- type %MYDIR%\my.log

build_script:
- date

after_success:
- dir %MYDIR%
- type %MYDIR%\my.log
