version: '{build}'
image:
- Previous Visual Studio 2013
- Visual Studio 2013
- Previous Visual Studio 2015
- Visual Studio 2015
- Previous Visual Studio 2017
- Visual Studio 2017

build_script:
- where git
- dir /n/b/s c:\git.*

test: off
