version: '{build}'
image:
- Visual Studio 2017
- Visual Studio 2019
configuration:
- Release
# - Debug
platform:
- x64
- Win32

init:
- echo Platform before == %Platform%
# Set developer command prompt
- if "%VS160COMNTOOLS%"=="" if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" set "VS160COMNTOOLS=%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Community\Common7\Tools\"
- if "%VS150COMNTOOLS%"=="" if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" set "VS150COMNTOOLS=%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\Common7\Tools\"
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" set "vcvarsall=%VS150COMNTOOLS%..\..\VC\Auxiliary\Build\vcvarsall.bat"
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" set "vcvarsall=%VS160COMNTOOLS%..\..\VC\Auxiliary\Build\vcvarsall.bat"
- if %platform:~-2%==64 (set arch=amd64) else (set arch=amd64_x86)
- call "%vcvarsall%" %arch%
- echo Platform final == %Platform%
# Print some info
- echo %APPVEYOR_BUILD_WORKER_IMAGE% %platform% %configuration% %arch%
# - cmake --version

build_script:
- mkdir build & cd build
- if %platform:~-2%==64 set "gen= Win64"
- if %platform:~-2%==64 (set "cmakeplatf=x64") else (set "cmakeplatf=Win32")
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" cmake -T host=x64 -G "Visual Studio 15 2017%gen%" .. || exit 0
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" cmake -T host=x64 -G "Visual Studio 16 2019" -A %cmakeplatf% .. || exit 0
- type CMakeFiles\3.15.5\VCTargetsPath.vcxproj
- cmake --build . --target testbin --config %configuration%
    -- /maxcpucount /verbosity:minimal /nologo /p:PreferredToolArchitecture=x64
